fluent-bit:
  config:
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host elasticsearch-master
          Logstash_Format On
          Retry_Limit False
          tls On
          tls.verify Off
          HTTP_User elastic
          HTTP_Passwd 1q77aPs1fLU0R20g
      [OUTPUT]
          Name es
          Match host.*
          Host elasticsearch-master
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False
          tls On
          tls.verify Off
          HTTP_User elastic
          HTTP_Passwd 1q77aPs1fLU0R20g