fluent-bit:
  config:
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
          Labels Off
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host elasticsearch-master
          Logstash_Format On
          Retry_Limit False
          tls On
          tls.verify Off
          Trace_Error On
          net.keepalive On
          Buffer_Size 25M
          Suppress_Type_Name On
          HTTP_User elastic
          HTTP_Passwd permanentCustomElasticPassword
          Replace_Dots On
      [OUTPUT]
          Name es
          Match host.*
          Host elasticsearch-master
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False
          tls On
          tls.verify Off
          Suppress_Type_Name On
          Trace_Error On
          net.keepalive On
          Buffer_Size 25M
          HTTP_User elastic
          HTTP_Passwd permanentCustomElasticPassword
          Replace_Dots On