apiVersion: v2
name: traefik-ingress
description: Traefik with ingress rules
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: traefik
    version: 20.6.0
    repository: https://traefik.github.io/charts