traefik:
  # Enables permanent HTTP to HTTPS redirection for all incoming requests
  ports:
    web:
      redirectTo: websecure

  ingressRoute:
    dashboard:
      enabled: true
      # Additional ingressRoute annotations (e.g. for kubernetes.io/ingress.class)
      annotations: {}
      # Additional ingressRoute labels (e.g. for filtering IngressRoute by custom labels)
      labels: {}
      # The router match rule used for the dashboard ingressRoute
      matchRule: Host(`traefik.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      # Specify the allowed entrypoints to use for the dashboard ingress route, (e.g. traefik, web, websecure).
      # By default, it's using traefik entrypoint, which is not exposed.
      # /!\ Do not expose your dashboard without any protection over the internet /!\
      entryPoints: ["websecure"]
      # Additional ingressRoute middlewares (e.g. for authentication)
      middlewares: []

