apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-developer
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  source:
    targetRevision: main