apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

commonLabels:
  env: dev

patchesStrategicMerge:
- argocd-developer/application.yaml
- efk-stack/application.yaml
- kibana/application.yaml
- grafana-dashboards/application.yaml
- k8s-dashboard/application.yaml
- kube-prometheus-stack/application.yaml
- traefik/application.yaml