apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

commonLabels:
  env: dev

patchesStrategicMerge:
- traefik/application.yaml
- argocd-developer/application.yaml
- kube-prometheus-stack/application.yaml