apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd-developer/application.yaml
- k8s-dashboard/application.yaml
- grafana-dashboards/application.yaml

- kube-prometheus-stack/application.yaml
- kube-prometheus-stack/projects.yaml

- traefik/application.yaml
- traefik/projects.yaml