apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik/projects.yaml
  - traefik/application.yaml
  - kube-prometheus-stack/projects.yaml
  - kube-prometheus-stack/application.yaml
  - argocd-developer/application.yaml