kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
  namespace: argocd
data:
  admin.enabled: 'true'
  kustomize.buildOptions: --enable-helm
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: c694265060d3407ce0c3
          clientSecret: INSERT-CLIENT-SECRET-HERE
          orgs:
            - name: AndrVelich-org
          loadAllGroups: true
  exec.enabled: 'false'
  url: https://argocd.local.k8s-infrastructure.com
  resource.customizations: |
    extensions/Ingress:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs