apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: elastic-search
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: efk-stack
    server: "https://kubernetes.default.svc"
  source:
    path: efk-stack/elastic-search
    repoURL: "https://github.com/AndrVelich/k8s-infrastructure.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
