elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  clusterHealthCheckParams: 'wait_for_status=yellow&timeout=1s'

  esJavaOpts: "-Xms512m -Xmx512m"

  resources:
    requests:
      cpu: "500m"
      memory: "1024Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi"

  secret:
    password: "permanentCustomElasticPassword"