apiVersion: v2
name: kube-prometheus-stack-configured
description: kube-prometheus-stack helm chart with configuration
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: kube-prometheus-stack
  version: 43.1.1
  repository: https://prometheus-community.github.io/helm-charts