apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-metrics
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`metrics.local.com`) && PathPrefix(`/metrics`)
      services:
        - name: prometheus@internal
          kind: TraefikService