apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    release: kube-prometheus-stack
spec:
  receivers:
  - name: 'null'
  - name: 'email'
    emailConfigs:
    - to: andr.velich@gmail.com
      from: andr.velich@outlook.com
      smarthost: smtp.sendgrid.net:587
      authUsername: apikey
      authPassword:
        key: password
        name: smtp-alertmanager 
      sendResolved: true
      text: 'Email from alert manager'

  route:
    groupBy: ['namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'null'
    routes:
    - receiver: 'email'
      matchers:
      - name: alertname
        matchType: '=~'
        value: "KubePodCrashLooping" 
  