apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik-metrics
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
  namespaceSelector:
    matchNames:
      - traefik