apiVersion: v1
kind: Secret
metadata:
  name: traefik-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://traefik.github.io/charts
  name: traefik
  type: helm