elasticsearch:
  replicas: 1
  minimumMasterNodes: 1

  esJavaOpts: "-Xms512m -Xmx512m"

  resources:
    requests:
      cpu: "500m"
      memory: "1024Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi"

fluent-bit:
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-master
        Logstash_Format On
        Retry_Limit False
        tls             On
        tls.verify      Off
    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        tls             On
        tls.verify      Off