apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

commonLabels:
  env: dev

patchesStrategicMerge:
- businesscard/application.yaml
- traefik/application.yaml
- ingress/argocd-ingressroute.yaml